### ISSUE TITLE
Readme file update request

### ISSUE THREAD

**Issue by eklahari** [atanumandal0491/Attentive-Fusion#1]
Hi atanumandal0491

I couldn't understand the process of executing the repository of hate speech detection you have mentioned . Could you please update your Readme file with detailed step by step procedure of execution the code files .If possible can you also mention the pictures of code execution in the environment you have worked like Google Colab or command prompt and final accuracy scores.

**Comment by atanumandal0491** [comment]
Hi,
For the preprocessing of the dataset, we created TFRecords. Download the repository and create the training file as per your requirements. The model is given in the repository.
